<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lyndsey Umsted">

<title>Forecasting the United States’ Theoretical Unemployment Rate in the Absence of the Covid-19 Pandemic</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Final_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/quarto.js"></script>
<script src="Final_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final_Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final_Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#training-and-testing-sets" id="toc-training-and-testing-sets" class="nav-link" data-scroll-target="#training-and-testing-sets">Training and Testing Sets</a></li>
  <li><a href="#analyzing-time-series-plot-of-training-set" id="toc-analyzing-time-series-plot-of-training-set" class="nav-link" data-scroll-target="#analyzing-time-series-plot-of-training-set">Analyzing Time Series Plot of Training Set</a></li>
  <li><a href="#transformation" id="toc-transformation" class="nav-link" data-scroll-target="#transformation">Transformation</a></li>
  <li><a href="#differencing" id="toc-differencing" class="nav-link" data-scroll-target="#differencing">Differencing</a>
  <ul class="collapse">
  <li><a href="#differencing-at-lag-1" id="toc-differencing-at-lag-1" class="nav-link" data-scroll-target="#differencing-at-lag-1">Differencing at Lag 1</a></li>
  <li><a href="#differencing-at-lag-12" id="toc-differencing-at-lag-12" class="nav-link" data-scroll-target="#differencing-at-lag-12">Differencing at Lag 12</a></li>
  <li><a href="#comparing-differenced-data" id="toc-comparing-differenced-data" class="nav-link" data-scroll-target="#comparing-differenced-data">Comparing Differenced Data</a></li>
  </ul></li>
  <li><a href="#identifying-preliminary-models" id="toc-identifying-preliminary-models" class="nav-link" data-scroll-target="#identifying-preliminary-models">Identifying Preliminary Models</a>
  <ul class="collapse">
  <li><a href="#identifying-coefficients-and-model-summaries" id="toc-identifying-coefficients-and-model-summaries" class="nav-link" data-scroll-target="#identifying-coefficients-and-model-summaries">Identifying Coefficients and Model Summaries</a></li>
  </ul></li>
  <li><a href="#comparing-models" id="toc-comparing-models" class="nav-link" data-scroll-target="#comparing-models">Comparing Models</a></li>
  <li><a href="#residual-analysis-and-diagnostic-checking" id="toc-residual-analysis-and-diagnostic-checking" class="nav-link" data-scroll-target="#residual-analysis-and-diagnostic-checking">Residual Analysis and Diagnostic Checking</a>
  <ul class="collapse">
  <li><a href="#visualizing-residuals" id="toc-visualizing-residuals" class="nav-link" data-scroll-target="#visualizing-residuals">Visualizing Residuals</a></li>
  <li><a href="#acf-and-pacf-plots-of-residuals" id="toc-acf-and-pacf-plots-of-residuals" class="nav-link" data-scroll-target="#acf-and-pacf-plots-of-residuals">ACF and PACF Plots of Residuals</a></li>
  <li><a href="#visualizing-residuals-1" id="toc-visualizing-residuals-1" class="nav-link" data-scroll-target="#visualizing-residuals-1">Visualizing Residuals</a></li>
  <li><a href="#acf-and-pacf-plots-of-residuals-1" id="toc-acf-and-pacf-plots-of-residuals-1" class="nav-link" data-scroll-target="#acf-and-pacf-plots-of-residuals-1">ACF and PACF Plots of Residuals</a></li>
  <li><a href="#shapiro-wilk-test-of-normality" id="toc-shapiro-wilk-test-of-normality" class="nav-link" data-scroll-target="#shapiro-wilk-test-of-normality">Shapiro-Wilk Test of Normality</a></li>
  <li><a href="#portmanteau-statistics" id="toc-portmanteau-statistics" class="nav-link" data-scroll-target="#portmanteau-statistics">Portmanteau Statistics</a></li>
  </ul></li>
  <li><a href="#forecasting" id="toc-forecasting" class="nav-link" data-scroll-target="#forecasting">Forecasting</a>
  <ul class="collapse">
  <li><a href="#forecasting-on-transformed-data" id="toc-forecasting-on-transformed-data" class="nav-link" data-scroll-target="#forecasting-on-transformed-data">Forecasting on Transformed Data</a></li>
  <li><a href="#forecasting-on-original-data" id="toc-forecasting-on-original-data" class="nav-link" data-scroll-target="#forecasting-on-original-data">Forecasting on Original Data</a></li>
  <li><a href="#forecasting-through-2023" id="toc-forecasting-through-2023" class="nav-link" data-scroll-target="#forecasting-through-2023">Forecasting through 2023</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Forecasting the United States’ Theoretical Unemployment Rate in the Absence of the Covid-19 Pandemic</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lyndsey Umsted </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>The purpose of this time series project is to forecast the United States’ unemployment rate into the years 2020 through 2023 using data from 2010 through 2018 with 2019 as validation. The main questions addressed in this analysis are: how do the predicted unemployment levels from January of 2020 to the present differ from the observations seen with the Covid-19 Pandemic? Are the unemployment rates in the past three to four years much higher than what a predictive model would forecast?</p>
<p>By using a Box-Cox transformation to stabilize the variance and then differencing to detrend and deseasonalilze the data, I was able to examine the Autocorrelation Function coefficients to identify preliminary Seasonal Auto Regressive Integrated Moving Average (SARIMA) models. By comparing the Akaike Information Criterion of the final stationary and invertible candidate models, a SARIMA(3,1,1)(0,1,1) s=12 model was identified as the best model. Residual analysis and diagnostic checking was performed on the fitted model to determine its appropriateness to forecast future values.</p>
<p>Using the fitted model, I was able to validate the model’s ability to forecast into the year 2019. I then observed and compared the model’s predicted values with the actual time series of the United State’s unemployment rate through October of 2023. I found that not only do current unemployment rates lie above the forecast 95% confidence interval, but they are also two times higher than the predicted unemployment rate, meaning twice as many Americans are out of work than what the SARIMA model forecasts in the absence of the Covid-19 Pandemic.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This time series analysis project uses data on the United States’ unemployment rate reported in percentage values at monthly increments. The data was obtained from the Federal Reserve Economic Data of the Federal Reserve Bank of St.&nbsp;Louis. The unemployment rate is calculated as the number of unemployed persons as a percentage of the labor force. The labor force is considered as people 16 years old or above within the United States, who do not reside in institutions (penal, mental, homes for aged), and are not on active duty in the military. The original data contains the unemployment rate between January, 1949 and October, 2023. As a reflection of economic stability, the unemployment rate is highly dependent on economic events such as recessions that can be seen in past years. Due to the Great Recession of 2008 which doubled the unemployment rate in one year (Duggan, 2023), this project begins with data from January, 2010 and onward for forecasting purposes.</p>
<p>The Covid-19 Pandemic induced a recession in 2020 where businesses suspended operations or closed in some cases resulting in large numbers of layoffs that increased the unemployment rate from 3.4% in December of 2019 to a high of 14.4% in April of 2020 (“Unemployment Rate (UNRATENSA)”, 2023). This anomalous event spiked the unemployment rate in a short period of time, and as businesses reopened and Covid-19 was contained, this number has decreased again to almost pre-pandemic rates.</p>
<p>Using data from 2010 to 2018, leaving 2019 for validation, I want to predict the unemployment rate into the years 2020 through 2023 and compare and contrast these predicted values to the observed unemployment rate time series during and after the Covid-19 Pandemic.</p>
<p>Forecasting unemployment rates is important to measure future economic stability. Being able to compare predictions to observations when an anomalous event happens allows us to measure the impact significance to prepare for future events.</p>
<p>Below we can visualize the observed unemployment rate from January of 2010 to the present:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A closer look at the Pandemic:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="training-and-testing-sets" class="level2">
<h2 class="anchored" data-anchor-id="training-and-testing-sets">Training and Testing Sets</h2>
<p>I will be using the years 2010-2018 for the training set and will leave the year 2019 as the testing set for validation of forecasts.</p>
</section>
<section id="analyzing-time-series-plot-of-training-set" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-time-series-plot-of-training-set">Analyzing Time Series Plot of Training Set</h2>
<p>Below is the time series plot of the training set or data from 01-01-2010 to 12-01-2018:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot shows a clear negative trend, as well as seasonality that follows a period of 12 months. There also appears to be a slight change in variance over time.</p>
</section>
<section id="transformation" class="level2">
<h2 class="anchored" data-anchor-id="transformation">Transformation</h2>
<p>Taking a look at a histogram of the data will give more information on if the data should be transformed after seeing that there is non constant variance.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram is not normal, so I will check a Box-Cox transformation.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2626263</code></pre>
</div>
</div>
<p>The optimal value of lambda is 0.2626263, so I will use this value to transform the data with the following transformation:</p>
<p><span class="math display">\[
X = Original Data
\]</span> <span class="math display">\[
Y = Transformed\space Data
\]</span></p>
<p><span class="math display">\[
Y = (X^\lambda - 1)/\lambda
\]</span> Thus: <span class="math display">\[
Transformed \space Data = ({Original \space Data}^{0.2626263} - 1)/0.2626263
\]</span></p>
<p>Taking a look at the time series plot of the Box-Cox transformed data:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The variance appears more stable. I will also look at the histogram of the transformed data:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram of the transformed data is not more normal than the original data, however the variance has decreased from 4.084399 to 0.2274075 so I will keep the Box-Cox transformation.</p>
</section>
<section id="differencing" class="level2">
<h2 class="anchored" data-anchor-id="differencing">Differencing</h2>
<p>I will examine the Decomposition of the transformed data to determine the neccessity for differencing.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is a clear trend and seasonality shown in the decomposition.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The slow decay seen in the ACF plot of the transformed data indicates non-stationarity and there is also visible seasonality. I will begin by differencing at lag 1 to account for the trend in the time series.</p>
<section id="differencing-at-lag-1" class="level3">
<h3 class="anchored" data-anchor-id="differencing-at-lag-1">Differencing at Lag 1</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The time series plot of the transformed data differenced at lag 1 shows constant mean and variance with no trend. I will also look at the ACF plot to check for seasonality.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The ACF plot indicates the data is still not stationary, so I will difference at lag 12 to account for the seasonality in the data.</p>
</section>
<section id="differencing-at-lag-12" class="level3">
<h3 class="anchored" data-anchor-id="differencing-at-lag-12">Differencing at Lag 12</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The time series plot of the transformed data differenced at lag 12 shows constant mean and variance with no trend. I will also look at the ACF plot to check for stationarity.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>ACF decay corresponds to a stationary process.</p>
</section>
<section id="comparing-differenced-data" class="level3">
<h3 class="anchored" data-anchor-id="comparing-differenced-data">Comparing Differenced Data</h3>
<p>I will take a look at the histograms one more time to compare the normality of the transformed data and its differences.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Box-Cox transformed data differenced at lag 1 and 12 appears to be more normally distributed than the others, as well as having decreased variance, therefore I will continue with this data to identify the preliminary models.</p>
</section>
</section>
<section id="identifying-preliminary-models" class="level2">
<h2 class="anchored" data-anchor-id="identifying-preliminary-models">Identifying Preliminary Models</h2>
<p>To identify the candidate models, I will look at the ACF and PACF plots of the transformed data differenced at Lags 1 and 12.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>Frist considerations:</p>
<ul>
<li><p>The ACF plot shows large spikes at lags 1, 7, and 12. Some SMA models to consider are:</p>
<ul>
<li><p>SARIMA(0,1,1)(0,1,1) s=12</p></li>
<li><p>SARIMA(0,1,7)(0,1,1) s=12</p></li>
</ul></li>
<li><p>I am also considering MA(12).</p></li>
</ul></li>
<li><p>Second considerations</p>
<ul>
<li><p>I am also keeping in mind that the ACF could be oscillating, which could suggest an AR or SAR model:</p></li>
<li><p>The PACF plot shows large coefficients at lags 1, 2, 3, 11, and 12. An SAR model to try:</p>
<ul>
<li>SARIMA(1,1,0)(1,1,0) s=12</li>
</ul></li>
<li><p>I am also considering AR(12).</p></li>
</ul></li>
</ul>
<section id="identifying-coefficients-and-model-summaries" class="level3">
<h3 class="anchored" data-anchor-id="identifying-coefficients-and-model-summaries">Identifying Coefficients and Model Summaries</h3>
<section id="sarima011011-s12" class="level4">
<h4 class="anchored" data-anchor-id="sarima011011-s12">SARIMA(0,1,1)(0,1,1) s=12:</h4>
<p>I will begin with the first candidate model: SARIMA(0,1,1)(0,1,1) s=12. Below is a summary of the fitted model.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(0, 1, 1), seasonal = list(order = c(0, 
    1, 1), period = 12), method = "ML")

Coefficients:
          ma1     sma1
      -0.4433  -0.8196
s.e.   0.1288   0.1655

sigma^2 estimated as 0.001568:  log likelihood = 165.33,  aic = -324.65

Training set error measures:
                       ME      RMSE       MAE         MPE     MAPE      MASE
Training set -0.000581133 0.0371597 0.0283185 -0.02039254 1.311623 0.3975893
                   ACF1
Training set 0.09180784</code></pre>
</div>
</div>
<p>Both coefficients are within (-1,1) indicating the model is invertible. I will note that the AICc value is -324.65.</p>
</section>
<section id="sarima017011-s12" class="level4">
<h4 class="anchored" data-anchor-id="sarima017011-s12">SARIMA(0,1,7)(0,1,1) s=12</h4>
<p>Second, I have the candidate model: SARIMA(0,1,7)(0,1,1) s=12. Below is a summary of the fitted model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(0, 1, 7), seasonal = list(order = c(0, 
    1, 1), period = 12), method = "ML")

Coefficients:
          ma1      ma2      ma3      ma4     ma5     ma6      ma7     sma1
      -0.4058  -0.0748  -0.1606  -0.0814  0.2641  0.2601  -0.1529  -0.9998
s.e.   0.1051   0.1135   0.1018   0.1211  0.1005  0.1230   0.1083   0.2879

sigma^2 estimated as 0.001146:  log likelihood = 172.75,  aic = -327.5

Training set error measures:
                        ME       RMSE        MAE         MPE     MAPE      MASE
Training set -0.0003788741 0.03177519 0.02361649 -0.01123808 1.092566 0.3315735
                    ACF1
Training set 0.006856686</code></pre>
</div>
</div>
<p>Using the coefficient 95% confidence intervals, I see that 0 lies within the confidence intervals at coefficients ma2, ma3, ma4, and ma7. Fixing for this, we then have the following summary.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(0, 1, 7), seasonal = list(order = c(0, 
    1, 0), period = 12), fixed = c(NA, 0, 0, 0, NA, NA, 0), method = "ML")

Coefficients:
          ma1  ma2  ma3  ma4     ma5     ma6  ma7
      -0.3912    0    0    0  0.3124  0.4353    0
s.e.   0.1579    0    0    0  0.1168  0.2030    0

sigma^2 estimated as 0.002201:  log likelihood = 151.7,  aic = -295.39

Training set error measures:
                       ME       RMSE        MAE        MPE     MAPE      MASE
Training set 0.0003164417 0.04401965 0.03226212 0.02220789 1.501236 0.4529574
                   ACF1
Training set -0.0134093</code></pre>
</div>
</div>
<p>This model has an AICc of -295.39, however I need to check that the model is invertible. Below is a visualization of the roots (red) of the MA polynomial.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Since not all roots of the MA polynomial lie outside the unit circle, the model is not invertible. The SARIMA(0,1,1)(0,1,1) s=12 remains as the candidate for now.</p>
</section>
<section id="ma12" class="level4">
<h4 class="anchored" data-anchor-id="ma12">MA(12)</h4>
<p>Next, I have the summary of the fitted MA(12) model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(0, 1, 12), seasonal = list(order = c(0, 
    1, 0), period = 12), method = "ML")

Coefficients:
          ma1      ma2      ma3     ma4     ma5     ma6      ma7     ma8
      -0.3204  -0.0557  -0.2956  0.0568  0.1955  0.0822  -0.1458  0.0071
s.e.   0.1420   0.1444   0.1297  0.1324  0.1471  0.1428   0.1282  0.1442
          ma9    ma10     ma11     ma12
      -0.0863  0.2991  -0.0090  -0.7278
s.e.   0.1493  0.1315   0.1888   0.1591

sigma^2 estimated as 0.00132:  log likelihood = 171.51,  aic = -317.02

Training set error measures:
                       ME       RMSE        MAE        MPE     MAPE      MASE
Training set -0.000618592 0.03408784 0.02563461 -0.0111135 1.186016 0.3599077
                    ACF1
Training set -0.09433029</code></pre>
</div>
</div>
<p>Using the coefficient 95% confidence intervals, I see that 0 lies within the confidence intervals at coefficients ma2, ma4, ma5, ma6, ma7, ma8, ma9, and ma11. Fixing for this, we then have the following summary.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(0, 1, 12), seasonal = list(order = c(0, 
    1, 0), period = 12), fixed = c(NA, 0, NA, 0, 0, 0, 0, 0, 0, NA, 0, NA), 
    method = "ML")

Coefficients:
          ma1  ma2      ma3  ma4  ma5  ma6  ma7  ma8  ma9    ma10  ma11
      -0.3020    0  -0.2158    0    0    0    0    0    0  0.2743     0
s.e.   0.0877    0   0.1137    0    0    0    0    0    0  0.1050     0
         ma12
      -0.8042
s.e.   0.1520

sigma^2 estimated as 0.001369:  log likelihood = 168.77,  aic = -327.55

Training set error measures:
                        ME       RMSE        MAE         MPE     MAPE      MASE
Training set -0.0008435405 0.03472159 0.02576233 -0.02913239 1.184669 0.3617009
                   ACF1
Training set -0.0923251</code></pre>
</div>
</div>
<p>There is now a 0 within the confidence interval for the ma3 coefficient. So the final model summary for the MA(12) model is below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(0, 1, 12), seasonal = list(order = c(0, 
    1, 0), period = 12), fixed = c(NA, 0, 0, 0, 0, 0, 0, 0, 0, NA, 0, NA), method = "ML")

Coefficients:
          ma1  ma2  ma3  ma4  ma5  ma6  ma7  ma8  ma9    ma10  ma11     ma12
      -0.3457    0    0    0    0    0    0    0    0  0.3354     0  -0.9446
s.e.   0.1182    0    0    0    0    0    0    0    0  0.1425     0   0.1516

sigma^2 estimated as 0.001235:  log likelihood = 167.21,  aic = -326.42

Training set error measures:
                        ME       RMSE        MAE         MPE     MAPE      MASE
Training set -0.0006159509 0.03297398 0.02492804 -0.01655869 1.144232 0.3499876
                  ACF1
Training set -0.112986</code></pre>
</div>
</div>
<p>This model has an AICc value of -326.42, however I need to check that the model is invertible. Below is a visualization of the roots (red) of the MA polynomial.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Since not all roots of the MA polynomial lie outside the unit circle, the model is not invertible. The SARIMA(0,1,1)(0,1,1) s=12 remains as the candidate for now.</p>
</section>
<section id="sarima110110-s12" class="level4">
<h4 class="anchored" data-anchor-id="sarima110110-s12">SARIMA(1,1,0)(1,1,0) s=12</h4>
<p>Due to the possible decay I saw in the ACF plot of the differenced data, I am also considering the SARIMA(1,1,0)(1,1,0) s=12 model and below is a summary of the fitted model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(1, 1, 0), seasonal = list(order = c(1, 
    1, 0), period = 12), method = "ML")

Coefficients:
          ar1     sar1
      -0.2172  -0.5605
s.e.   0.1005   0.0818

sigma^2 estimated as 0.001904:  log likelihood = 160.45,  aic = -314.9

Training set error measures:
                       ME       RMSE        MAE        MPE     MAPE      MASE
Training set 0.0003003032 0.04093835 0.03163286 0.02096746 1.469947 0.4441226
                    ACF1
Training set -0.02973299</code></pre>
</div>
</div>
<p>Both coefficients are within (-1,1), indicating the model is stationary. I will note that the AICc value is -314.9</p>
</section>
<section id="ar12" class="level4">
<h4 class="anchored" data-anchor-id="ar12">AR(12)</h4>
<p>Next I have the summary of the fitted AR(12) model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(12, 1, 0), seasonal = list(order = c(0, 
    1, 0), period = 12), method = "ML")

Coefficients:
          ar1      ar2      ar3      ar4      ar5     ar6      ar7      ar8
      -0.2831  -0.1303  -0.1247  -0.0834  -0.0196  0.1251  -0.0998  -0.0368
s.e.   0.0946   0.0970   0.0966   0.0989   0.1001  0.1032   0.1001   0.0997
         ar9    ar10    ar11     ar12
      0.0430  0.1708  0.1729  -0.3894
s.e.  0.1007  0.1050  0.1049   0.0994

sigma^2 estimated as 0.001625:  log likelihood = 168.11,  aic = -310.22

Training set error measures:
                       ME       RMSE        MAE        MPE     MAPE      MASE
Training set 0.0002981154 0.03782493 0.02797456 0.02067937 1.293941 0.3927603
                   ACF1
Training set -0.0084127</code></pre>
</div>
</div>
<p>Using the coefficient 95% confidence intervals, I see that 0 lies within the confidence intervals at coefficients ar2, ar3, ar4, ar5, ar6, ar7, ar8, ar9, ar10, and ar11. Fixing for this, we then have the following summary.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(12, 1, 0), seasonal = list(order = c(0, 
    1, 0), period = 12), fixed = c(NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA), method = "ML")

Coefficients:
          ar1  ar2  ar3  ar4  ar5  ar6  ar7  ar8  ar9  ar10  ar11     ar12
      -0.1135    0    0    0    0    0    0    0    0     0     0  -0.5415
s.e.   0.0831    0    0    0    0    0    0    0    0     0     0   0.0834

sigma^2 estimated as 0.001965:  log likelihood = 159.1,  aic = -312.2

Training set error measures:
                       ME      RMSE        MAE        MPE     MAPE      MASE
Training set 0.0003152606 0.0415873 0.03190487 0.02248603 1.479125 0.4479416
                   ACF1
Training set -0.1071929</code></pre>
</div>
</div>
<p>There is now a 0 within the confidence interval for the ar1 coefficient. So the final model summary for the MA(12) model is below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(12, 1, 0), seasonal = list(order = c(0, 
    1, 0), period = 12), fixed = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA), method = "ML")

Coefficients:
      ar1  ar2  ar3  ar4  ar5  ar6  ar7  ar8  ar9  ar10  ar11     ar12
        0    0    0    0    0    0    0    0    0     0     0  -0.5637
s.e.    0    0    0    0    0    0    0    0    0     0     0   0.0817

sigma^2 estimated as 0.001997:  log likelihood = 158.17,  aic = -312.34

Training set error measures:
                       ME       RMSE        MAE        MPE     MAPE      MASE
Training set 0.0003058091 0.04192702 0.03239767 0.02188477 1.499944 0.4548605
                   ACF1
Training set -0.2133004</code></pre>
</div>
</div>
<p>The only coefficient left is for ar12 and it is within (-1,1) thus the model is stationary. I will note that the AICc value is -312.34</p>
</section>
</section>
</section>
<section id="comparing-models" class="level2">
<h2 class="anchored" data-anchor-id="comparing-models">Comparing Models</h2>
<p>The candidate models which are both stationary and invertible have the following AICc values:</p>
<ul>
<li><p>SARIMA(0,1,1)(0,1,1) s=12</p>
<ul>
<li>AICc = -324.65</li>
</ul></li>
<li><p>SARIMA(1,1,0)(1,1,0) s=12</p>
<ul>
<li>AICc = -314.9</li>
</ul></li>
<li><p>AR(12)</p>
<ul>
<li>AICc = -312.34</li>
</ul></li>
</ul>
<p>Based on this information, I will continue with the SARIMA(0,1,1)(0,1,1) s=12 model for diagnostic checking since it has the lowest AICc value of -324.65.</p>
<section id="chosen-model-sarima011011-s12" class="level4">
<h4 class="anchored" data-anchor-id="chosen-model-sarima011011-s12">Chosen Model: SARIMA(0,1,1)(0,1,1) s=12</h4>
<p><span class="math display">\[
(1-B)(1-B^{12}){X_t} = (1+0.4433B)(1+0.8196B^{12}){Z_t} \space \space
\]</span> <span class="math display">\[
Where \space {Z_t} \sim WN(0,{\sigma_Z}^2)
\]</span></p>
</section>
</section>
<section id="residual-analysis-and-diagnostic-checking" class="level2">
<h2 class="anchored" data-anchor-id="residual-analysis-and-diagnostic-checking">Residual Analysis and Diagnostic Checking</h2>
<section id="visualizing-residuals" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-residuals">Visualizing Residuals</h3>
<p>Below are visualizations of the SARIMA(0,1,1)(0,1,1) s=12 model’s residuals to check that they are Gaussian and follow a White Noise pattern.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plotted residuals do resemble white noise and the trend and mean appear to coincide at about 0. The residuals distribution is approximately normal centered at 0. In the qq plot, the dots do follow close to the line.</p>
</section>
<section id="acf-and-pacf-plots-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="acf-and-pacf-plots-of-residuals">ACF and PACF Plots of Residuals</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-31-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I want all coefficients at lags &gt; 1 to be within the confidence intervals. There are a few lags that have coefficients slightly outside the confidence interval, so I will check if my residuals are white noise using the ar() command:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ar(x = residuals, aic = TRUE, order.max = NULL, method = c("yule-walker"))

Coefficients:
      1        2        3  
 0.0732  -0.1273  -0.2159  

Order selected 3  sigma^2 estimated as  0.001325</code></pre>
</div>
</div>
<p>The output of this shows that I need to add 3 to p in my model and test the model: SARIMA(3,1,1)(0,1,1) s=12:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = bc_unemployment, order = c(3, 1, 1), seasonal = list(order = c(0, 
    1, 1), period = 12), method = "ML")

Coefficients:
          ar1      ar2     ar3      ma1     sma1
      -0.0050  -0.1554  -0.267  -0.3538  -0.9899
s.e.   0.1996   0.1116   0.111   0.1887   0.6673

sigma^2 estimated as 0.001258:  log likelihood = 169.53,  aic = -327.06

Training set error measures:
                       ME       RMSE        MAE         MPE     MAPE      MASE
Training set -0.001009832 0.03328663 0.02493871 -0.03410548 1.157935 0.3501373
                    ACF1
Training set -0.02363977</code></pre>
</div>
</div>
<p>I will now analyze the residuals of this model.</p>
</section>
<section id="visualizing-residuals-1" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-residuals-1">Visualizing Residuals</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plotted residuals do resemble white noise and the trend and mean appear to coincide at about 0. The residuals distribution is approximately normal centered at 0. In the qq plot, the dots do follow close to the line.</p>
</section>
<section id="acf-and-pacf-plots-of-residuals-1" class="level3">
<h3 class="anchored" data-anchor-id="acf-and-pacf-plots-of-residuals-1">ACF and PACF Plots of Residuals</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>All of the coefficients lie within the confidence interval! I will continue to the following tests.</p>
</section>
<section id="shapiro-wilk-test-of-normality" class="level3">
<h3 class="anchored" data-anchor-id="shapiro-wilk-test-of-normality">Shapiro-Wilk Test of Normality</h3>
<p>I will also be using the Shapiro-Wilk Test to check that the residuals are normally distributed.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals
W = 0.9829, p-value = 0.1809</code></pre>
</div>
</div>
<p>The p-value is 0.1809, which is larger than 0.05, so I fail to reject the normality hypothesis of the residuals.</p>
</section>
<section id="portmanteau-statistics" class="level3">
<h3 class="anchored" data-anchor-id="portmanteau-statistics">Portmanteau Statistics</h3>
<p>Another part of diagnostic checking are the Portmanteau Statistics, checking for p-values &lt; 0.05.</p>
<p>Both the Box-Pierce and Ljung-Box Tests are to test for linear dependence of the residuals. Since there are 108 observations in the training set, lag = 10, and since I have 5 estimated coefficients (ar1, ar2, ar3, ma1, and sma1) the fitdf = 5 for these two tests.</p>
<p>The McLeod-Li Test is to test if the residuals are correlated and uses the same lag = 10 and fitdf = 0.</p>
<section id="box-pierce-test" class="level4">
<h4 class="anchored" data-anchor-id="box-pierce-test">Box-Pierce Test</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Pierce test

data:  residuals
X-squared = 8.3883, df = 5, p-value = 0.1361</code></pre>
</div>
</div>
</section>
<section id="ljung-box-test" class="level4">
<h4 class="anchored" data-anchor-id="ljung-box-test">Ljung-Box Test</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  residuals
X-squared = 9.1427, df = 5, p-value = 0.1035</code></pre>
</div>
</div>
</section>
<section id="mcleod-li-test" class="level4">
<h4 class="anchored" data-anchor-id="mcleod-li-test">McLeod-Li Test</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  residuals^2
X-squared = 9.8049, df = 10, p-value = 0.4578</code></pre>
</div>
</div>
<p>P-values for both the Box-Pierce and Ljung-Box Tests are above 0.05, meaning I fail to reject the hypothesis that the residuals are linearly independent.</p>
<p>The p-value for the McLeod-Li Test is greater than 0.05, meaning I fail to reject the hypothesis that the residuals are uncorrelated.</p>
<p>This model appears to work the best out of all candidates, so I will continue to forecasting based on the residuals passing all diagnostic checks.</p>
</section>
<section id="chosen-model-sarima311011-s12" class="level4">
<h4 class="anchored" data-anchor-id="chosen-model-sarima311011-s12">Chosen Model: SARIMA(3,1,1)(0,1,1) s=12</h4>
<p><span class="math display">\[ (1 + 0.005B + 0.1554B^2 + 0.267B^3)(1-B)(1-B^{12}){X_t} = (1-0.9899B^{12})(1 - 0.3538B){Z_t} \space \space \]</span> <span class="math display">\[ Where \space {Z_t} \sim WN(0,{\sigma_Z}^2) \]</span></p>
</section>
</section>
</section>
<section id="forecasting" class="level2">
<h2 class="anchored" data-anchor-id="forecasting">Forecasting</h2>
<section id="forecasting-on-transformed-data" class="level3">
<h3 class="anchored" data-anchor-id="forecasting-on-transformed-data">Forecasting on Transformed Data</h3>
<p>Below are the plotted forecast values on the Box-Cox transformed data</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-40-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="forecasting-on-original-data" class="level3">
<h3 class="anchored" data-anchor-id="forecasting-on-original-data">Forecasting on Original Data</h3>
<p>After transforming the predicted values back to the original data values, below are the plotted forecast values on the original unemployment data as well as the test set values.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Below is a closer look at the model’s predicted values (green) compared to the observed test values (red) as well as the 95% confidence interval for forecast values (blue).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looking to the test values (red) which almost all lie within the 95% confidence interval, I am able to validate the SARIMA(3,1,1)(0,1,1) s=12 model’s ability to accurately forecast unemployment rates into the year 2019.</p>
</section>
<section id="forecasting-through-2023" class="level3">
<h3 class="anchored" data-anchor-id="forecasting-through-2023">Forecasting through 2023</h3>
<p>Below is the predicted unemployment rate time series through the years 2020-2023 as compared to the observed times series.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can take a closer look at the years 2019 through October, 2023.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While the observed unemployment values of 2019 appear to coincide with the prediction intervals, there is a large difference beginning in early 2020. Unemployment rates remain much higher than the predicted interval until the end of 2021. From the beginning of 2022 and up through October of 2023, unemployment rates are still higher than the upper side of the prediction interval.</p>
<p>The predicted unemployment rate for October of 2023 based on data from 2010 to 2018 is 1.98%, whereas the observed unemployment rate at the beginning of October this year was 3.6%, almost twice as high. Because of the seasonality, the best comparison to pre-pandemic levels would be the October prior to the start of the Pandemic. The unemployment rate at the beginning of October, 2019 was 3.3% so levels are still higher. It would be interesting to compare the unemployment rate of March, 2024 to March, 2020 to see if unemployment finally decreases to pre-pandemic levels.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The goal of this project was to forecast unemployment rates through 2023 using data from 2010-2018 fitted to a Seasonal Autoregressive Integrated Moving Average (SARIMA) model.</p>
<p>Using the SARIMA(3,1,1)(0,1,1) s=12 model:</p>
<p><span class="math display">\[
(1 + 0.005B + 0.1554B^2 + 0.267B^3)(1-B)(1-B^{12}){X_t} = (1-0.9899B^{12})(1 - 0.3538B){Z_t} \space \space
\]</span> <span class="math display">\[ Where \space {Z_t} \sim WN(0,{\sigma_Z}^2) \]</span></p>
<p>I hoped to compare and contrast the unemployment rates observed during and after the Covid-19 Pandemic to the predicted values. I found there was a large spike in the unemployment rate during the beginning months of 2020 which decreased during the second half of the year, but did not decrease to pre-pandemic levels until 2022, and were still slightly higher. Based on the trend seen for the unemployment level from 2010 to 2018, the unemployment rate is predicted to be just 1.98% in October, and 1.97% on December 1, 2023. These predictions are proportionally about half of what the unemployment levels are today, meaning twice as many Americans are out of work than what this model predicts if the Covid-19 Pandemic had not occurred.</p>
<p>That being said, anomalous events have occurred throughout American history that disrupt the trend in unemployment levels, therefore something else could have impacted unemployment rates during this time without the Pandemic. It is worth noting that April, 2020 did mark the largest unemployment rate in United States’ history since 1940 after the lasting effects of the Great Depression (Amadeo, 2022). Comparing these forecast values to the unemployment rates observed after the Covid-19 Pandemic can help national and state governments prepare for the impact another anomalous event may have on the unemployment rate, and then predict the amount of time it may take to reach unemployment levels prior to the event.</p>
<p>I want to acknowledge Professor Raisa Feldman and Teaching Assistant Cosmin Borsa for guiding me through this project and providing assistance and understanding.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Amadeo, Kimberly. “Historical US Unemployment Rate by Year.” <em>The Balance</em>, The Balance, 6 Dec.&nbsp;2022, www.thebalancemoney.com/unemployment-rate-by-year-3305506#:~:text=The%20highest%20rate%20of%20U.S.,14%25%20from%201931%20to%201940.</p>
<p>Duggan, Wayne. “A Short h=History of the Great Recession.” <em>Forbes</em>, Forbes Magazine, 21 June 2023, www.forbes.com/advisor/investing/great-recession/#:~:text=The%20Great%20Recession%20of%202008,down%2057%25%20from%20its%20highs.),.</p>
<p>“Unemployment Rate (UNRATENSA).” <em>FRED</em>, 3 Nov.&nbsp;2023, fred.stlouisfed.org/series/UNRATENSA.</p>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">Appendix</h2>
<p>The following is code for each of the visuals, model summaries, and tests performed in this report.</p>
<section id="visualizing-unemployment-time-series-from-2010-to-present" class="level5">
<h5 class="anchored" data-anchor-id="visualizing-unemployment-time-series-from-2010-to-present">Visualizing unemployment time series from 2010 to present:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>unemployment <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/unemployment.csv"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># converting to datetime object </span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>unemployment[[<span class="st">'Date'</span>]] <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(unemployment[[<span class="dv">1</span>]],</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">format =</span><span class="st">"%Y-%d-%m"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>unemployment_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(unemployment<span class="sc">$</span>unemployment , <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2010</span>,<span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2023</span>,<span class="dv">10</span>))</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize data from 2010 to present</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(unemployment_ts, <span class="at">ylab =</span> <span class="st">"unemployment (%)"</span>, <span class="at">main =</span> <span class="st">"The United States' Unemployment Rate From 2010 to Present"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">c</span>(<span class="fl">2020.2</span>,<span class="dv">3</span>), <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="fl">2017.75</span>,<span class="dv">3</span>), <span class="at">y =</span> <span class="dv">12</span>,<span class="st">"First Lockdown -</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="st">     March 2020"</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="zoomed-in-time-series" class="level5">
<h5 class="anchored" data-anchor-id="zoomed-in-time-series">Zoomed in time series:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>unemployment_ts2 <span class="ot">&lt;-</span> <span class="fu">ts</span>(unemployment<span class="sc">$</span>unemployment[<span class="dv">97</span><span class="sc">:</span><span class="dv">166</span>], <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2018</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2023</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize data from 2010 to present</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(unemployment_ts2, <span class="at">ylab =</span> <span class="st">"unemployment (%)"</span>, <span class="at">main =</span> <span class="st">"The United States' Unemployment Rate During the Covid-19 Pandemic"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="fl">2020.26</span>), <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="fl">2021.75</span>), <span class="at">y =</span> <span class="dv">11</span>,<span class="st">"- Highest Unemployement</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="st">     Rate at 14.4%</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="st">     (April, 2020)"</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="training-and-testing-sets-1" class="level5">
<h5 class="anchored" data-anchor-id="training-and-testing-sets-1">Training and testing sets:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> unemployment_ts[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">108</span>)]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># leaving out 12 data points for testing set</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> unemployment_ts[<span class="fu">c</span>(<span class="dv">109</span><span class="sc">:</span><span class="dv">120</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="time-series-plot-of-training-set" class="level5">
<h5 class="anchored" data-anchor-id="time-series-plot-of-training-set">Time series plot of training set:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(train),train, <span class="at">main =</span> <span class="st">"Time Series of Training Set</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="st">     (2010-2018)"</span>, <span class="at">type =</span> <span class="st">'l'</span>,<span class="at">xlab=</span><span class="st">'index'</span>, <span class="at">ylab =</span> <span class="st">"unemployment (%)"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>index <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span> <span class="fu">length</span>(train)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>trend <span class="ot">&lt;-</span> <span class="fu">lm</span>(train <span class="sc">~</span> index)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(trend, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(train) , <span class="at">col=</span><span class="st">'blue'</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">80</span>), <span class="at">y =</span> <span class="fl">7.5</span>,<span class="st">"Mean Unemployment</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="st">     Rate = 6.51%"</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="histogram-of-training-data" class="level5">
<h5 class="anchored" data-anchor-id="histogram-of-training-data">Histogram of training data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(train, <span class="at">col=</span><span class="st">"light blue"</span>, <span class="at">xlab=</span><span class="st">""</span>, <span class="at">main=</span><span class="st">"histogram; unemployment data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="box-cox-diagram-and-lambda-value" class="level5">
<h5 class="anchored" data-anchor-id="box-cox-diagram-and-lambda-value">Box-Cox diagram and lambda value:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>bcTransform <span class="ot">&lt;-</span> <span class="fu">boxcox</span>(train<span class="sc">~</span><span class="fu">as.numeric</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(train)))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># optimal lambda</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> bcTransform<span class="sc">$</span>x[<span class="fu">which</span>(bcTransform<span class="sc">$</span>y <span class="sc">==</span> <span class="fu">max</span>(bcTransform<span class="sc">$</span>y))]</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="time-series-plot-of-box-cox-transformed-data" class="level5">
<h5 class="anchored" data-anchor-id="time-series-plot-of-box-cox-transformed-data">Time series plot of Box-Cox transformed data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>bc_unemployment <span class="ot">&lt;-</span> lambda<span class="sc">**</span>(<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(train<span class="sc">**</span>(lambda) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(bc_unemployment),bc_unemployment, <span class="at">main =</span> <span class="st">"Time Series of Box-Cox Transformed Data"</span>, <span class="at">type =</span> <span class="st">'l'</span>,<span class="at">xlab=</span><span class="st">'index'</span>, <span class="at">ylab=</span><span class="st">"unemployment (%)"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>index <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span> <span class="fu">length</span>(bc_unemployment)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>trend <span class="ot">&lt;-</span> <span class="fu">lm</span>(bc_unemployment <span class="sc">~</span> index)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(trend, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(bc_unemployment) , <span class="at">col=</span><span class="st">'blue'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="histogram-of-box-cox-transformed-data" class="level5">
<h5 class="anchored" data-anchor-id="histogram-of-box-cox-transformed-data">Histogram of Box-Cox transformed data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bc_unemployment, <span class="at">col=</span><span class="st">"light blue"</span>, <span class="at">xlab=</span><span class="st">""</span>, <span class="at">main=</span><span class="st">"histogram; Box-Cox Transformed unemployment data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="decomposition-of-box-cox-transformed-data" class="level5">
<h5 class="anchored" data-anchor-id="decomposition-of-box-cox-transformed-data">Decomposition of Box-Cox transformed data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ggplot2")</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ggfortify")</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">as.ts</span>(bc_unemployment), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>decomp <span class="ot">&lt;-</span> <span class="fu">decompose</span>(y)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(decomp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="acf-plot-of-box-cox-transformed-data" class="level5">
<h5 class="anchored" data-anchor-id="acf-plot-of-box-cox-transformed-data">ACF plot of Box-Cox transformed data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(bc_unemployment,<span class="at">lag.max=</span><span class="dv">60</span>, <span class="at">main=</span><span class="st">"ACF of the Box-Cox Transformed Unemployment Data"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="differencing-box-cox-transformed-data-at-lag-1-and-plotting-time-series" class="level5">
<h5 class="anchored" data-anchor-id="differencing-box-cox-transformed-data-at-lag-1-and-plotting-time-series">Differencing Box-Cox transformed data at lag 1 and plotting time series:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dunemployment <span class="ot">&lt;-</span> <span class="fu">diff</span>(bc_unemployment, <span class="dv">1</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(dunemployment),dunemployment, <span class="at">main =</span> <span class="st">"Transformed Data Differenced at Lag 1"</span>, <span class="at">type =</span> <span class="st">'l'</span>,<span class="at">xlab=</span><span class="st">'index'</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>index <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span> <span class="fu">length</span>(dunemployment)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>trend <span class="ot">&lt;-</span> <span class="fu">lm</span>(dunemployment <span class="sc">~</span> index)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(trend, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(dunemployment) , <span class="at">col=</span><span class="st">'blue'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="acf-of-data-differenced-at-lag-1" class="level5">
<h5 class="anchored" data-anchor-id="acf-of-data-differenced-at-lag-1">ACF of data differenced at lag 1:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(dunemployment,<span class="at">lag.max=</span><span class="dv">60</span>, <span class="at">main=</span><span class="st">"ACF of the Transformed Data Differenced at Lag 1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="differencing-box-cox-transformed-data-at-lag-12-and-plotting-time-series" class="level5">
<h5 class="anchored" data-anchor-id="differencing-box-cox-transformed-data-at-lag-12-and-plotting-time-series">Differencing Box-Cox transformed data at lag 12 and plotting time series:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>ddunemployment <span class="ot">&lt;-</span> <span class="fu">diff</span>(dunemployment, <span class="dv">12</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(ddunemployment),ddunemployment, <span class="at">main =</span> <span class="st">"Time Series"</span>, <span class="at">type =</span> <span class="st">'l'</span>,<span class="at">xlab=</span><span class="st">'index'</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>index <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span> <span class="fu">length</span>(ddunemployment)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>trend <span class="ot">&lt;-</span> <span class="fu">lm</span>(ddunemployment <span class="sc">~</span> index)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(trend, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(ddunemployment) , <span class="at">col=</span><span class="st">'blue'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="acf-of-data-differenced-at-lag-1-and-12" class="level5">
<h5 class="anchored" data-anchor-id="acf-of-data-differenced-at-lag-1-and-12">ACF of data differenced at lag 1 and 12:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(ddunemployment,<span class="at">lag.max=</span><span class="dv">60</span>, <span class="at">main=</span><span class="st">"ACF of the Transformed Data Differenced at Lag 1 and 12"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="histograms-of-box-cox-and-differenced-data" class="level5">
<h5 class="anchored" data-anchor-id="histograms-of-box-cox-and-differenced-data">Histograms of Box-Cox and differenced data</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bc_unemployment, <span class="at">col=</span><span class="st">"light blue"</span>, <span class="at">xlab=</span><span class="st">""</span>, <span class="at">main=</span><span class="st">"histogram; Box-Cox Transformed unemployment data"</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dunemployment, <span class="at">col=</span><span class="st">"light blue"</span>, <span class="at">xlab=</span><span class="st">""</span>, <span class="at">main=</span><span class="st">"histogram; Box-Cox Transformed unemployment data differenced at lag 1"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ddunemployment, <span class="at">col=</span><span class="st">"light blue"</span>, <span class="at">xlab=</span><span class="st">""</span>, <span class="at">main=</span><span class="st">"histogram; Box-Cox Transformed unemployment data differenced at lag 1 and 12"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="acf-and-pacf-plots-of-differenced-data" class="level5">
<h5 class="anchored" data-anchor-id="acf-and-pacf-plots-of-differenced-data">ACF and PACF plots of differenced data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(ddunemployment,<span class="at">lag.max=</span><span class="dv">60</span>, <span class="at">main=</span><span class="st">"ACF"</span>) </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(ddunemployment,<span class="at">lag.max=</span><span class="dv">60</span>, <span class="at">main=</span><span class="st">"PACF"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-sarima011011-s12-model" class="level5">
<h5 class="anchored" data-anchor-id="fitting-sarima011011-s12-model">Fitting SARIMA(0,1,1)(0,1,1) s=12 model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-sarima017011-s12-model" class="level5">
<h5 class="anchored" data-anchor-id="fitting-sarima017011-s12-model">Fitting SARIMA(0,1,7)(0,1,1) s=12 model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast) </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">7</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>) </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fixing-sarima017011-s12-model" class="level5">
<h5 class="anchored" data-anchor-id="fixing-sarima017011-s12-model">Fixing SARIMA(0,1,7)(0,1,1) s=12 model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">7</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>, <span class="at">fixed =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="dv">0</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-roots-of-sarima017011-s12-model" class="level5">
<h5 class="anchored" data-anchor-id="plotting-roots-of-sarima017011-s12-model">Plotting roots of SARIMA(0,1,7)(0,1,1) s=12 model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../labs/plot.roots.r"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.roots</span>(<span class="cn">NULL</span>,<span class="fu">polyroot</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.3912</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.3124</span>,<span class="fl">0.4353</span>,<span class="dv">0</span>)), <span class="at">main=</span><span class="st">"roots of MA model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-ma12-model" class="level5">
<h5 class="anchored" data-anchor-id="fitting-ma12-model">Fitting MA(12) model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">12</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fixing-ma12-model" class="level5">
<h5 class="anchored" data-anchor-id="fixing-ma12-model">Fixing MA(12) model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">12</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>, <span class="at">fixed =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">0</span>,<span class="cn">NA</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="cn">NA</span>,<span class="dv">0</span>,<span class="cn">NA</span>))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">12</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>, <span class="at">fixed =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="cn">NA</span>,<span class="dv">0</span>,<span class="cn">NA</span>))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-roots-of-ma12-model" class="level5">
<h5 class="anchored" data-anchor-id="plotting-roots-of-ma12-model">Plotting roots of MA(12) model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../labs/plot.roots.r"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.roots</span>(<span class="cn">NULL</span>,<span class="fu">polyroot</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.3457</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.3354</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="fl">0.9446</span>)), <span class="at">main=</span><span class="st">"roots of MA model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-sarima110110-s12-model" class="level5">
<h5 class="anchored" data-anchor-id="fitting-sarima110110-s12-model">Fitting SARIMA(1,1,0)(1,1,0) s=12 model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-ar12-model" class="level5">
<h5 class="anchored" data-anchor-id="fitting-ar12-model">Fitting AR(12) model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fixing-ar12-model" class="level5">
<h5 class="anchored" data-anchor-id="fixing-ar12-model">Fixing AR(12) model:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>, <span class="at">fixed =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="cn">NA</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>, <span class="at">fixed =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="cn">NA</span>))</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arma_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualizing-model-residuals" class="level5">
<h5 class="anchored" data-anchor-id="visualizing-model-residuals">Visualizing model residuals:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>arma_model <span class="ot">&lt;-</span> <span class="fu">arima</span>(bc_unemployment, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">seasonal =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">period =</span> <span class="dv">12</span>), <span class="at">method=</span><span class="st">"ML"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">residuals</span>(arma_model)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting residuals</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(residuals, <span class="at">main=</span><span class="st">"Plot of residuals"</span>)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(1:length(time_series),time_series, main =</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="co"># "Time Series", type = 'l',xlab='index')</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>index <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span> <span class="fu">length</span>(residuals)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>trend <span class="ot">&lt;-</span> <span class="fu">lm</span>(residuals <span class="sc">~</span> index)</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(trend, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(residuals) , <span class="at">col=</span><span class="st">'blue'</span>)</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the histogram of the residuals:</span></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(residuals)</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a><span class="co">#q-q plot</span></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(residuals)</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="acf-and-pacf-plots-of-residuals-2" class="level5">
<h5 class="anchored" data-anchor-id="acf-and-pacf-plots-of-residuals-2">ACF and PACF plots of residuals:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(residuals)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="ar-command" class="level5">
<h5 class="anchored" data-anchor-id="ar-command">AR() command</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ar</span>(residuals, <span class="at">aic =</span> <span class="cn">TRUE</span>, <span class="at">order.max =</span> <span class="cn">NULL</span>, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"yule-walker"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="shapiro-wilk-test-of-normality-1" class="level5">
<h5 class="anchored" data-anchor-id="shapiro-wilk-test-of-normality-1">Shapiro-Wilk Test of Normality:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Shapiro test for normality</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="portmanteau-statistics-1" class="level5">
<h5 class="anchored" data-anchor-id="portmanteau-statistics-1">Portmanteau Statistics</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Box-Pierce test</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(residuals, <span class="at">lag =</span> <span class="dv">10</span>, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"Box-Pierce"</span>), <span class="at">fitdf =</span> <span class="dv">2</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Ljung-Box test</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(residuals, <span class="at">lag =</span> <span class="dv">10</span>, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"Ljung-Box"</span>), <span class="at">fitdf =</span> <span class="dv">2</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co">#McLeod-Li test</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(residuals<span class="sc">^</span><span class="dv">2</span>, <span class="at">lag =</span> <span class="dv">10</span>, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"Ljung-Box"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forecasting-on-box-cox-transformed-data" class="level5">
<h5 class="anchored" data-anchor-id="forecasting-on-box-cox-transformed-data">Forecasting on Box-Cox transformed data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>pred.tr <span class="ot">&lt;-</span> <span class="fu">predict</span>(arma_model, <span class="at">n.ahead =</span> <span class="dv">12</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>U.tr<span class="ot">=</span> pred.tr<span class="sc">$</span>pred <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>pred.tr<span class="sc">$</span>se</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>L.tr<span class="ot">=</span> pred.tr<span class="sc">$</span>pred <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>pred.tr<span class="sc">$</span>se</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(bc_unemployment, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fu">length</span>(bc_unemployment)<span class="sc">+</span><span class="dv">12</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(L.tr),<span class="fu">max</span>(bc_unemployment)), <span class="at">main =</span> <span class="st">"Forecasted Predictions on Transformed Data"</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(U.tr, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(L.tr, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>((<span class="fu">length</span>(bc_unemployment)<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="fu">length</span>(bc_unemployment)<span class="sc">+</span><span class="dv">12</span>), pred.tr<span class="sc">$</span>pred, <span class="at">col=</span><span class="st">"green"</span>)</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a><span class="co"># zoom in</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(bc_unemployment, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">97</span>,<span class="fu">length</span>(bc_unemployment)<span class="sc">+</span><span class="dv">12</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(L.tr),<span class="fu">max</span>(U.tr)), <span class="at">main =</span> <span class="st">"Forecasted Predictions on Transformed Data"</span>)</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(U.tr, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(L.tr, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>((<span class="fu">length</span>(bc_unemployment)<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="fu">length</span>(bc_unemployment)<span class="sc">+</span><span class="dv">12</span>), pred.tr<span class="sc">$</span>pred, <span class="at">col=</span><span class="st">"green"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forecasting-on-original-data-1" class="level5">
<h5 class="anchored" data-anchor-id="forecasting-on-original-data-1">Forecasting on original data:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>pred.tr <span class="ot">&lt;-</span> <span class="fu">predict</span>(arma_model, <span class="at">n.ahead =</span> <span class="dv">12</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>pred.orig <span class="ot">&lt;-</span> ((pred.tr<span class="sc">$</span>pred<span class="sc">/</span>lambda<span class="sc">**</span>(<span class="sc">-</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>lambda)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>U <span class="ot">=</span> ((U.tr<span class="sc">/</span>lambda<span class="sc">**</span>(<span class="sc">-</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>lambda)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>L <span class="ot">=</span> ((L.tr<span class="sc">/</span>lambda<span class="sc">**</span>(<span class="sc">-</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>lambda)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(train, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fu">length</span>(train)), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(L),<span class="fu">max</span>(unemployment_ts)), <span class="at">ylab=</span><span class="st">"unemployment(%)"</span>, <span class="at">main =</span> <span class="st">"Forecasted Predictions on Original Data"</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(U, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(L, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>((<span class="fu">length</span>(train)<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="fu">length</span>(train)<span class="sc">+</span><span class="dv">12</span>), pred.orig, <span class="at">col=</span><span class="st">"green"</span>)</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>((<span class="fu">length</span>(test)<span class="sc">+</span><span class="dv">97</span>)<span class="sc">:</span>(<span class="fu">length</span>(test)<span class="sc">+</span><span class="dv">108</span>), test, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forecasting-on-original-data---test-set-comparison" class="level5">
<h5 class="anchored" data-anchor-id="forecasting-on-original-data---test-set-comparison">Forecasting on original data - test set comparison:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># zoom in</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(train, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">109</span>,<span class="fu">length</span>(train)<span class="sc">+</span><span class="dv">12</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(L),<span class="fu">max</span>(U)),<span class="at">ylab=</span><span class="st">"unemployment(%)"</span>, <span class="at">main =</span> <span class="st">"Forecasted Predictions on Original Data"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(U, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(L, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>((<span class="fu">length</span>(train)<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="fu">length</span>(train)<span class="sc">+</span><span class="dv">12</span>), pred.orig, <span class="at">col=</span><span class="st">"green"</span>)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>((<span class="fu">length</span>(test)<span class="sc">+</span><span class="dv">97</span>)<span class="sc">:</span>(<span class="fu">length</span>(test)<span class="sc">+</span><span class="dv">108</span>), test, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forecasting-through-2023-1" class="level5">
<h5 class="anchored" data-anchor-id="forecasting-through-2023-1">Forecasting through 2023:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>pred.tr <span class="ot">&lt;-</span> <span class="fu">predict</span>(arma_model, <span class="at">n.ahead =</span> <span class="dv">60</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>U.tr<span class="ot">=</span> pred.tr<span class="sc">$</span>pred <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>pred.tr<span class="sc">$</span>se</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>L.tr<span class="ot">=</span> pred.tr<span class="sc">$</span>pred <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>pred.tr<span class="sc">$</span>se</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>pred.orig <span class="ot">&lt;-</span> ((pred.tr<span class="sc">$</span>pred<span class="sc">/</span>lambda<span class="sc">**</span>(<span class="sc">-</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>lambda)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>U <span class="ot">=</span> ((U.tr<span class="sc">/</span>lambda<span class="sc">**</span>(<span class="sc">-</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>lambda)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>L <span class="ot">=</span> ((L.tr<span class="sc">/</span>lambda<span class="sc">**</span>(<span class="sc">-</span><span class="dv">1</span>)) <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>lambda)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(unemployment<span class="sc">$</span>unemployment, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fu">length</span>(unemployment_ts)), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(L),<span class="fu">max</span>(unemployment<span class="sc">$</span>unemployment)), <span class="at">main =</span> <span class="st">"Forecasted Predictions on Original Data"</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(U, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(L, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>((<span class="fu">length</span>(train)<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>(<span class="fu">length</span>(train)<span class="sc">+</span><span class="dv">60</span>), pred.orig, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forecasting-through-2023-2019-2023" class="level5">
<h5 class="anchored" data-anchor-id="forecasting-through-2023-2019-2023">Forecasting through 2023 (2019-2023):</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>pandemic <span class="ot">&lt;-</span> <span class="fu">ts</span>(unemployment<span class="sc">$</span>unemployment[<span class="dv">109</span><span class="sc">:</span><span class="dv">166</span>], <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2019</span>,<span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2023</span>,<span class="dv">10</span>))</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">ts</span>(pred.orig, <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2019</span>,<span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2023</span>,<span class="dv">10</span>))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co"># zoom in</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>U <span class="ot">=</span> <span class="fu">ts</span>(U, <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2019</span>,<span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2023</span>,<span class="dv">10</span>))</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>L <span class="ot">=</span> <span class="fu">ts</span>(L, <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2019</span>,<span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2023</span>,<span class="dv">10</span>))</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(pandemic, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(L), <span class="fu">max</span>(pandemic)), <span class="at">ylab =</span> <span class="st">"unemployment (%)"</span>, <span class="at">main =</span> <span class="st">"Forecasted Predictions on Original Data"</span>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(U, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(L, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">lty=</span><span class="st">"dashed"</span>)</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(pred, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">c</span>(<span class="fl">2020.17</span>,<span class="dv">3</span>), <span class="at">col =</span> <span class="st">"purple"</span>)</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="fl">2019.5</span>,<span class="dv">3</span>), <span class="at">y =</span> <span class="dv">12</span>,<span class="st">"First Lockdown -</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a><span class="st">     March, 2020"</span>, <span class="at">col =</span> <span class="st">"purple"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comparing-predicted-values-to-observed-values" class="level5">
<h5 class="anchored" data-anchor-id="comparing-predicted-values-to-observed-values">Comparing predicted values to observed values:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>pred</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>pandemic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>